<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sales Report</title>
    <style>
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 1em; }
        th, td { padding: 8px; border: 1px solid #ddd; }
        th { background-color: #f4f4f4; }
        .summary-box {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 20px;
            display: inline-block;
            margin-right: 20px;
        }
        .header {
            margin-bottom: 20px;
        }
        .period {
            margin-bottom: 15px;
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="header text-center">
        <h2 style="text-transform: uppercase; margin: 5px 0;">{{ str_replace('CENTER', 'CENTRE', $setting->nama_perusahaan ?? 'COMPANY NAME') }}</h2>
        @if($setting && $setting->alamat)
        <p style="font-size: 11px; color: #666; margin: 3px 0;">{{ $setting->alamat }}</p>
        @endif
        <h3 style="margin: 10px 0;">Sales Report</h3>
        <div class="period">{{ $period }}</div>
    </div>

    <div>
        <div class="summary-box">
            <strong>Total Sales:</strong> Ksh {{ number_format($summary['total_sales'], 2) }}
        </div>
        <div class="summary-box">
            <strong>Total Transactions:</strong> {{ number_format($summary['total_transactions']) }}
        </div>
        <div class="summary-box">
            <strong>Average Sale:</strong> Ksh {{ number_format($summary['average_sale'], 2) }}
        </div>
        <div class="summary-box">
            <strong>Total Discount:</strong> Ksh {{ number_format($summary['total_discount'], 2) }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date/Period</th>
                <th>Transactions</th>
                <th>Items Sold</th>
                <th class="text-right">Total Sales</th>
                <th class="text-right">Average Sale</th>
                <th class="text-right">Discount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
            <tr>
                <td>{{ $row['period'] }}</td>
                <td>{{ number_format($row['total_transactions']) }}</td>
                <td>{{ number_format($row['total_items']) }}</td>
                <td class="text-right">Ksh {{ number_format($row['total_amount'], 2) }}</td>
                <td class="text-right">Ksh {{ number_format($row['average_sale'], 2) }}</td>
                <td class="text-right">Ksh {{ number_format($row['total_discount'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>Total</th>
                <th>{{ number_format($summary['total_transactions']) }}</th>
                <th>{{ number_format($summary['total_items']) }}</th>
                <th class="text-right">Ksh {{ number_format($summary['total_sales'], 2) }}</th>
                <th class="text-right">Ksh {{ number_format($summary['average_sale'], 2) }}</th>
                <th class="text-right">Ksh {{ number_format($summary['total_discount'], 2) }}</th>
            </tr>
        </tfoot>
    </table>

    <div style="margin-top: 20px;">
        <p><strong>Generated:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
