<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Product Report</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin: 10px 0;
            text-transform: uppercase;
        }
        .report-title {
            font-size: 20px;
            margin: 10px 0;
            color: #666;
        }
        .report-date {
            font-size: 14px;
            color: #666;
            margin-bottom: 20px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th,
        .table td {
            padding: 8px;
            border: 1px solid #ddd;
            font-size: 14px;
        }
        .table th {
            background-color: #f5f5f5;
            font-weight: bold;
            text-align: left;
        }
        .table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ str_replace('CENTER', 'CENTRE', strtoupper($setting->nama_perusahaan ?? 'COMPANY NAME')) }}</div>
        @if($setting && $setting->alamat)
        <div style="font-size: 12px; color: #666; margin: 5px 0;">{{ $setting->alamat }}</div>
        @endif
        <div class="report-title">Product Report</div>
        <div class="report-date">Generated: {{ now()->format('Y-m-d H:i:s') }}</div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th>Shop</th>
                <th>Supplier</th>
                <th>Item Code</th>
                <th>Product Name</th>
                <th class="text-right">Purchase Price</th>
                <th class="text-right">Selling Price</th>
                <th class="text-right">Stock</th>
                <th>MOP</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $key => $product)
            <tr>
                <td>{{ $key + 1 }}</td>
                <td>{{ $product->shop->shop_name ?? '-' }}</td>
                <td>{{ $product->supplier->nama ?? '-' }}</td>
                <td>{{ $product->item_code }}</td>
                <td>{{ $product->nama_produk }}</td>
                <td class="text-right">{{ number_format($product->harga_beli) }}</td>
                <td class="text-right">{{ number_format($product->harga_jual) }}</td>
                <td class="text-right">{{ number_format($product->stok) }}</td>
                <td>{{ $product->mop }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7" class="text-right"><strong>Total Stock:</strong></td>
                <td class="text-right"><strong>{{ number_format($products->sum('stok')) }}</strong></td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>Report generated by UTAMA POS System</p>
    </div>
</body>
</html>
